### ISSUE TITLE
Feature request: please add another setting to just to sanitise dsn hidden rolls whilst keeping attack rolls visibile.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [sPOiDar/fvtt-module-hide-gm-rolls#36] opened 2023-01-23 02:15 UTC
what currently happens is I either have the option to hide all rolls from players rather than just hidden/secret rolls from players and still display the dice from dice so nice. 

what i would like is a setting to just sanitise dsn rolls when its hidden/secret (pf2). so that players can see my attack rolls but not my secret rolls.

**Comment by sPOiDar** [comment] 2023-01-23 02:38
I'm not quite sure I follow. If you leave the option to sanitize DSN rolls disabled, I think it will already do what you want, since DSN should already respect private rolls?

**Comment by ThingsCouldGetDicey** [comment] 2023-01-23 03:05
> I'm not quite sure I follow. If you leave the option to sanitize DSN rolls disabled, I think it will already do what you want, since DSN should already respect private rolls?

if i roll for a secret roll i cannot roll without players seeing a dsn roll. so i have to have the setting to sanitise all rolls. i cannot just roll an attack roll with dsn rolls on.

**Comment by ThingsCouldGetDicey** [comment] 2023-01-23 03:09
![image](https://user-images.githubusercontent.com/62528192/213959499-7386ba3f-b39e-481f-b5f5-83a7980f6532.png)

i have these settings enabled but im forced to so that dsn doesnt roll the secret checks.

**Comment by ThingsCouldGetDicey** [comment] 2023-01-23 03:10
what id like is to have dsn sanatise only on secret/hidden checks. and not on public rolls.

**Comment by sPOiDar** [comment] 2023-01-23 03:28
> what id like is to have dsn sanatise only on secret/hidden checks. and not on public rolls.

This is what DSN should do by default - if DSN is showing dice to other players (you'll need to log in as a player to see) for a private roll, then either some other module is causing it, or DSN has a bug. Make sure your DSN version is up-to-date, and if you can reproduce with only DSN enabled, you should probably lodge a bug with them as rolling dice for other players on private rolls is not expected behaviour.

I'm going to close this out here, but feel free to re-open if you find that there's something this module should be doing to help, though that doesn't seem likely based on the description.

**Closed by sPOiDar** 2023-01-23 03:28 UTC
Labels: question

**Comment by ThingsCouldGetDicey** [comment] 2023-01-23 03:47
> > what id like is to have dsn sanatise only on secret/hidden checks. and not on public rolls.
> 
> This is what DSN should do by default - if DSN is showing dice to other players (you'll need to log in as a player to see) for a private roll, then either some other module is causing it, or DSN has a bug. Make sure your DSN version is up-to-date, and if you can reproduce with only DSN enabled, you should probably lodge a bug with them as rolling dice for other players on private rolls is not expected behaviour.
> 
> I'm going to close this out here, but feel free to re-open if you find that there's something this module should be doing to help, though that doesn't seem likely based on the description.

i can invite you to the game i think its the way secret rolls are treated in pf2.

**Comment by sPOiDar** [comment] 2023-01-23 04:16
I'm not sure what "secret rolls" are here, if that's a technical term used by pf2e, or just how you usually refer to private rolls - in Foundry, there's `Public Roll`, `Private GM Roll`, `Blind GM Roll`, and `Self Roll` - all chat message types other than `Public Roll` cause their content to be hidden from other players, and should cause DSN not to show dice. If pf2e doesn't use the built-in Foundry functionality to perform private rolls, then neither this module nor DSN will/can do the right thing.

It would surprise me if that is actually the case, but if it was I'd be asking them to reconsider and do things the normal way because I personally don't have much interest in supporting hacks for all the possible systems out there, especially for standard functionality that's included in core.

**Comment by ThingsCouldGetDicey** [comment] 2023-01-23 05:16
> I'm not sure what "secret rolls" are here, if that's a technical term used by pf2e, or just how you usually refer to private rolls - in Foundry, there's `Public Roll`, `Private GM Roll`, `Blind GM Roll`, and `Self Roll` - all chat message types other than `Public Roll` cause their content to be hidden from other players, and should cause DSN not to show dice. If pf2e doesn't use the built-in Foundry functionality to perform private rolls, then neither this module nor DSN will/can do the right thing.
> 
> It would surprise me if that is actually the case, but if it was I'd be asking pf2e to reconsider and do things the normal way because I personally don't have much interest in supporting hacks for all the possible systems out there, especially for standard functionality that's included in core.

secret rolls are just blind gm rolls. and dsn activates on those. as a standard thing with the mod. but i have to sanatise that to stop the blind rolls. as some rolls when exploring require secret perception checks but use the blind gm rolls.  so id like it if it were possible to hide blind gm rolls with the rolls from dsn. but still do public.

**Comment by sPOiDar** [comment] 2023-01-23 05:22
As I said earlier - if you're certain that DSN is activating for your players when you roll a blind GM roll, and your DSN is up-to-date, and it happens with no other modules enabled, that sounds like a DSN bug and you should report it, though I cannot reproduce what you're describing under those conditions.

**Comment by ThingsCouldGetDicey** [comment] 2023-01-23 06:06
> As I said earlier - if you're certain that DSN is activating for your players when you roll a blind GM roll, and your DSN is up-to-date, and it happens with no other modules enabled, that sounds like a DSN bug and you should report it, though I cannot reproduce what you're describing under those conditions.

"

ive done it and disabled all modules but i run on the forge and players can still see it as ive tested.

**Comment by ThingsCouldGetDicey** [comment] 2023-01-23 06:07
i can invite you to my game to test if you like

**Comment by ThingsCouldGetDicey** [comment] 2023-01-23 06:07
GuitarGuyNick#7895

**Comment by ThingsCouldGetDicey** [comment] 2023-01-23 06:24
> As I said earlier - if you're certain that DSN is activating for your players when you roll a blind GM roll, and your DSN is up-to-date, and it happens with no other modules enabled, that sounds like a DSN bug and you should report it, though I cannot reproduce what you're describing under those conditions.

i found the issue you were right. currently there is no way to seperate the permissions between gm and player for blind gm rolls to show as "ghosted" rolls.  so i wrote an issue to ask to split them.
