### ISSUE TITLE
Better Rolls 5e produces roll audio on hidden rolls

### ISSUE THREAD

**Issue by SLinxTheFox** [sPOiDar/fvtt-module-hide-gm-rolls#23] opened 2021-10-05 22:46 UTC
basically title sheet. everything works fine, but when I roll from a character sheet everybody can hear

**Comment by sPOiDar** [comment] 2021-10-05 22:53
Just to be clear, you're performing a private roll (roll type not set to `Public Roll`), and the roll message is hidden, but players are still hearing a sound? If so, please check to see if this happens without any other modules enabled.

**Comment by sPOiDar** [comment] 2021-10-06 00:15
Reported on Discord that Better Rolls causes roll sound to be played for players on hidden rolls, needs investigation to work out how they're doing that.

**Comment by sPOiDar** [comment] 2021-10-30 07:18
I cannot reproduce this - `Better Rolls for 5e` and `Hide GM Rolls` enabled, rolling a private roll as a GM, when `Hide Private GM Rolls` is enabled, does not produce any audio for players.

I'm going to close this for now - if you can provide more information, reproduce with just those two modules enabled, or find another module that's causing this issue, please reopen.

**Closed by sPOiDar** 2021-10-30 07:18 UTC
Labels: invalid, compatibility

**Comment by sPOiDar** [comment] 2021-10-30 08:01
Actually, I can reproduce, sometimes. Seems inconsistent, but they appear to be doing their own audio notifications in BR5E, completely bypassing the core chat notification system.

**Comment by sPOiDar** [comment] 2021-10-30 13:09
Unfortunately, the way Better Rolls is handling audio for chat messages means there's no way for me to identify what audio is triggered from a hidden roll, and what is triggered from a regular roll, and BR5E is not seeing much in the way of significant updates these days, so this doesn't seem likely to be fixed for the foreseeable future.

The only real option to fix this behaviour is to disable roll sounds entirely in the BR5E settings, but that will mean you don't get any roll audio at all, I'm afraid :disappointed:
