### ISSUE TITLE
Sanitize Rolls (actually) no longer working with Ready Set Rolls 5e

### ISSUE THREAD

**Issue by LostCarcosa** [sPOiDar/fvtt-module-hide-gm-rolls#42] opened 2024-06-09 00:44 UTC
On Foundry V11.315, D&D5e version 3.2.0

Foundry V11.315
DND5e Version 3.2.0
Ready Set Roll 5e Version 3.0.14

Sanitization of rolls no longer works with RSR5e; both attack rolls and crits are expandable by players. 

Module still behaves as expected without RSR5e.

![image](https://github.com/sPOiDar/fvtt-module-hide-gm-rolls/assets/62232382/f05f1e62-7fc7-4065-8f8d-994bbc91069d)

**Comment by sPOiDar** [comment] 2024-06-09 08:21
Duplicate of #41 

I don't use RSR, and haven't had time to look into how they've changed their markup to break compatibility with this module.

**Closed by sPOiDar** 2024-06-09 08:21 UTC
Labels: duplicate
